cfn changes

diff --git a/backend/sqs-ec2/cfn-backendyaml b/backend/sqs-ec2/cfn-backendyaml
--- a/backend/sqs-ec2/cfn-backendyaml
+++ b/backend/sqs-ec2/cfn-backendyaml
@@ -1,8 +1,18 @@
 AWSTemplateFormatVersion: 2010-09-09
-Description: EC2 Auto Scaling group using EC2 Spot Instances, automatically scaling
-  based on SQS queue depth
-  
+Description: EC2 Image Builder
+
 Parameters:
+  gitHubRepo:
+    Type: String
+    Default: https://github.com/UBC-CIC/COVID19-L3-Net-APP
+  gitHubBranch:
+    Default: master
+    Type: String 
+  Ec2KeyName:
+    Type: AWS::EC2::KeyPair::KeyName
+  amazonLinuxAmi:
+    Type: String 
+    Description: Deep Learning AMI (Amazon Linux 2)
   s3Bucket:
     Type: String
   desiredCapacity:
@@ -52,8 +62,187 @@ Parameters:
     Type: Number
     MinValue: 60
 
-
 Resources:
+  ImageBuilderLogBucket:
+    Type: AWS::S3::Bucket
+
+  InstanceRole:
+    Type: AWS::IAM::Role
+    Metadata:
+      Comment: Role to be used by instance during image build.
+    Properties:
+      ManagedPolicyArns:
+        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
+        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
+      AssumeRolePolicyDocument:
+        Statement:
+          - Action:
+              - sts:AssumeRole
+            Effect: Allow
+            Principal:
+              Service:
+                - ec2.amazonaws.com
+        Version: "2012-10-17"
+      Path: /executionServiceEC2Role/
+
+  InstanceRoleLoggingPolicy:
+    Type: AWS::IAM::Policy
+    Metadata:
+      Comment: Allows the instance to save log files to an S3 bucket.
+    Properties:
+      PolicyName: ImageBuilderLogBucketPolicy
+      Roles:
+        - Ref: InstanceRole
+      PolicyDocument:
+        Version: "2012-10-17"
+        Statement:
+          - Action:
+              - s3:PutObject
+            Effect: Allow
+            Resource:
+              - Fn::Sub:
+                  - arn:${AWS::Partition}:s3:::${BUCKET}/*
+                  - BUCKET:
+                      Ref: ImageBuilderLogBucket
+  InstanceProfile:
+    Type: AWS::IAM::InstanceProfile
+    Properties:
+      Path: /executionServiceEC2Role/
+      Roles:
+        - Ref: InstanceRole
+
+  ContainerBuildComponent:
+    Type: 'AWS::ImageBuilder::Component'
+    Properties:
+      Name: Covid19-Model-Builder
+      Platform: 'Linux'
+      Version: "1.0.0"
+      Description:
+        !Join
+          - ''
+          - - 'Covid19-Component-'
+            - !Ref gitHubBranch
+      ChangeDescription: 'change-description'
+      # Require one of 'Data' or 'Uri' for Component template
+      Data: 
+        !Sub 
+          - |-
+            name: Covid19Model - InlineData
+            description: Covid19 Model Load
+            schemaVersion: 1.0
+
+            phases:
+              - name: initialization
+                steps:
+                  - name: GitHubClone
+                    action: ExecuteBash
+                    inputs:
+                      commands:
+                        - yum -y install git awslogs jq imagemagick            
+                        - cd /tmp
+                        - sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm                      
+                        - sudo systemctl start amazon-ssm-agent || echo "Failed in starting SSM"
+                        
+
+              - name: build
+                steps:
+                  - name: ImageName
+                    action: ExecuteBash
+                    inputs:
+                      commands:
+                        - |
+                          if [[ "${gitBranch}" == "master" ]]; then
+                            echo "covid-19-api:latest"
+                          else
+                            echo "covid-19-api:${gitBranch}"
+                          fi
+
+                  - name: ModelBuild
+                    action: ExecuteBash
+                    inputs:
+                      commands:
+                        - cd /root && git clone ${gitHub}.git covid-19-app-${gitBranch} --branch ${gitBranch}
+                        - cd covid-19-app-${gitBranch}/backend/sqs-ec2
+                        - 'CONTAINER_IMAGE={{ build.ImageName.outputs.stdout }}'
+                        - cp -av ./spot-instance-interruption-notice-handler.service /etc/systemd/system/spot-instance-interruption-notice-handler.service
+                        - cp -av ./worker.service /etc/systemd/system/worker.service
+                        - cp -av ./spot-instance-interruption-notice-handler.sh /usr/local/bin/
+                        - cp -av ./worker.sh /usr/local/bin
+                        - chmod +x /usr/local/bin/spot-instance-interruption-notice-handler.sh
+                        - chmod +x /usr/local/bin/worker.sh           
+                        - docker pull public.ecr.aws/k1w5m7b3/$CONTAINER_IMAGE
+                        - docker tag public.ecr.aws/k1w5m7b3/$CONTAINER_IMAGE $CONTAINER_IMAGE
+          - gitHub: !Ref gitHubRepo
+            gitBranch: !Ref gitHubBranch
+
+  ImageRecipe:
+    Type: 'AWS::ImageBuilder::ImageRecipe'
+    Properties:
+      Name: Covid19-Model-Recipe
+      Description:
+        !Join
+          - ''
+          - - 'Covid19-Recipe-'
+            - !Ref gitHubBranch
+      Version: '1.0.0'
+      ParentImage: !Ref amazonLinuxAmi
+      Components:
+        - ComponentArn: !Ref ContainerBuildComponent
+
+  InfrastructureConfiguration:
+    Type: AWS::ImageBuilder::InfrastructureConfiguration
+    Properties:
+      Name: Covid19-Model-Infrastructure
+      Description:
+        !Join
+          - ''
+          - - 'Covid19-Infrastructure-'
+            - !Ref gitHubBranch
+      InstanceProfileName:
+        Ref: InstanceProfile
+      # Set of one or more instance types to use when building the instance. Image Builder will select a type
+      # based on availability.
+      InstanceTypes:
+        - 'g4dn.xlarge'
+        - 'g4dn.2xlarge'
+      # Specify an S3 bucket and EC2 Image Builder will save logs to the bucket.
+      Logging:
+        S3Logs:
+          S3BucketName:
+            Ref: ImageBuilderLogBucket
+          S3KeyPrefix: !Join [ "-", [ 'imagebuilder', !Ref "AWS::StackName" ] ]
+      # If you would like to keep the instance running after a failed build, set TerminateInstanceOnFailure to false.
+      TerminateInstanceOnFailure: true
+      # If you do not have a default VPC or want to use a different VPC, you must specify the IDs of a subnet and one or more
+      # security groups to be associated with the build instance.
+      SubnetId: '{{resolve:ssm:/covid19l3/subnet1:1}}' 
+      SecurityGroupIds: 
+        - '{{resolve:ssm:/covid19l3/securitygroup:1}}'
+
+  covid19l3Image:
+    Type: AWS::ImageBuilder::Image
+    Properties:
+      ImageRecipeArn:
+        Ref: ImageRecipe
+      InfrastructureConfigurationArn:
+        Ref: InfrastructureConfiguration
+
+  # Create an SSM Parameter Store entry with our resulting ImageId.
+  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html
+  ImageParameter:
+    Type: AWS::SSM::Parameter
+    Properties:
+      Description: Image Id for Covid19l3
+      Name: !Sub /covid19l3/${gitHubBranch}/imageid
+      Type: String
+      Value:
+        Fn::GetAtt: [covid19l3Image, ImageId]
+
+###################################################################################################
+#
+#    Background components
+#
+###################################################################################################
   originAccessIdentity:
     Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
     Properties: 
@@ -376,6 +565,7 @@ Resources:
     - instanceProfile
     - sqsQueue
     - cloudWatchLogsGroup
+    - covid19l3Image
     Properties:
       LaunchTemplateData:
         IamInstanceProfile:
@@ -384,7 +574,7 @@ Resources:
             - instanceProfile
             - Arn
         ImageId:
-          !Sub '{{resolve:ssm:/covid19l3/${gitHubBranch}/imageid:1}}'
+          Fn::GetAtt: [covid19l3Image, ImageId]
         KeyName: 
           Ref: Ec2KeyName
         TagSpecifications:
@@ -429,22 +619,3 @@ Resources:
         Version: 2012-10-17
       Queues:
       - Ref: sqsQueue
-          
-Outputs:
-  awsRegionId:
-    Description: The AWS Region ID your template was launched in
-    Value:
-      Ref: AWS::Region
-
-  sqsQueueName:
-    Description: The SQS queue ARN
-    Value:
-      Fn::GetAtt:
-      - sqsQueue
-      - QueueName
-
-  cloudFrontDomain:
-    Value:
-      Fn::GetAtt:
-      - cloudFront
-      - DomainName
